### ISSUE TITLE
Finish migrating to wasm-safe JS-interop

### ISSUE THREAD

**Issue by kevmoo** [a14n/dart-google-maps#125]
Sadly, v7.1.0 is still not ready for wasm.

`js_wrapping` is outdated and still uses `pkg:js`.
There is still a dependency on `pkg:js`.

**Comment by kevmoo** [comment]
How can we help here? Seems like `js_wrapping` is the culprit!

**Comment by a14n** [comment]
This is a real big task. Not sure to have enough free time in the next days/weeks :-/

**Comment by kevmoo** [comment]
@a14n – you've been a MACHINE here. Thanks for clearly communicating your limitations!

**Comment by JgomesAT** [comment]
We have some conflicts with libraries of use of package js the major part of libraries are updated to use js 0.7 but Google maps uses 0.6 is it possible to update to version 0.7.1?

**Comment by a14n** [comment]
I started working on a new version but it is a full rewrite and will take some time for it to land.

**Comment by kevmoo** [comment]
Any updates here @a14n ? anyway we can help?

**Comment by a14n** [comment]
I started a new generator based on scraping/parsing https://developers.google.com/maps/documentation/javascript/reference/.

There are some challenges:
- regarding types: e.g Dart type to use for JS union type like `LatLng|LatLngLiteral` ?
- trying to reduce changes to do for the migration
- dartify the api like the current google_maps package

I don't have a lot of free time to work on it. I will try to push some code on a branch once I have something clean.

**Comment by MagnusJohansson** [comment]
I'm also waiting for an update that addresses the dependency on the 3 year old js ^0.6.3, starting to get conflicts with other packages that uses 0.7.1.

I have also [seen this](https://github.com/dart-lang/sdk/tree/main/pkg/js), that might need to be taken into consideration for future updates.
`Important: Prefer using dart:js_interop instead of this package for JS interop. See the [JS interop documentation](https://dart.dev/interop/js-interop) for more details.`

**Comment by bziembanski** [comment]
Also having problems with old js version. I would really appreciate new resolved version

**Comment by a14n** [comment]
A little update on this migration/rewrite. I made great progress and it's close to have a pre-version to test. If someone is crazy enough to give it a stab the code lives in the [new-js-interop](https://github.com/a14n/dart-google-maps/tree/new-js-interop) branch. WARNING this is a working branch where force-pushes occurs regularly.

**Comment by Rexios80** [comment]
This was expected, but the new google_maps code is not a drop in replacement for the old version for anyone thinking of trying it

**Comment by a14n** [comment]
It took a long time but I just published `google_maps-8.0.0-dev.1`.

To migrate, here are the main points:

- `GMap` should be rename to `Map`
- `toJS` and `toDart` are sometimes required on elements accepting/returning several types
- some services now return Future instead of having a callback function

**Comment by kevmoo** [comment]
amazing! thank you! We'll try it out.

**Comment by Rexios80** [comment]
@kevmoo do you have a designated person to do the migration? If not I can try and do it.

**Comment by kevmoo** [comment]
@Rexios80 – want to run on this? https://github.com/flutter/packages/pull/7064

**Comment by Rexios80** [comment]
Sure! I can take a look next week.

**Comment by a14n** [comment]
Done via google_maps-8.0.0
